sudo: required
language: node_js
node_js:
  - '10'
python:
  - '3.5'
cache:
  - pip
  yarn: true
  directories:
    - node_modules
install:
  - pip install awscli
script:
  - yarn test
before_deploy:
  - yarn run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"